export type Theme = {
  dark: boolean;
  sideMenuColor: string;
  menuColor: string;
  selectedColor: string;
  selectedBackground: string;
  dragBackground: string;
  dragBorder: string;
  pane: string;
  headerBackground: string;
  textColor: string;
  meta: string;
  headerText: string;
  inverted: boolean;
  inputBackground: string;
  buttonBackground: string;
  headerColor: string;
  inputColor: string;
  inputLabel: string;
  borderColor: string;
  invalidColor: string;
  invalidBackground: string;
  label: string;
  inputBorder: string;
};
