import { Option } from '@toryjs/form';

export const fakerOptions = (): Option[] => [
  // { text: '-- ADDRESS --', value: 'Address', disabled: true },
  { value: '', text: '' },
  { text: '-- ADDRESS --', value: 'address', disabled: true },
  { value: 'address.zipCode', text: 'Zip Code' },
  { value: 'address.city', text: 'City' },
  { value: 'address.cityPrefix', text: 'City Prefix' },
  { value: 'address.citySuffix', text: 'City Suffix' },
  { value: 'address.streetName', text: 'Street Name' },
  { value: 'address.streetAddress', text: 'Street Address' },
  { value: 'address.streetSuffix', text: 'Street Suffix' },
  { value: 'address.streetPrefix', text: 'Street Prefix' },
  { value: 'address.secondaryAddress', text: 'Secondary Address' },
  { value: 'address.county', text: 'County' },
  { value: 'address.country', text: 'Country' },
  { value: 'address.countryCode', text: 'Country Code' },
  { value: 'address.state', text: 'State' },
  { value: 'address.stateAbbr', text: 'State Abbreviation' },
  { value: 'address.latitude', text: 'Latitude' },
  { value: 'address.longitude', text: 'Longitude' },
  { text: '-- COMMERCE --', value: 'commerce', disabled: true },
  { value: 'commerce.color', text: 'Color' },
  { value: 'commerce.department', text: 'Department' },
  { value: 'commerce.productName', text: 'Product Name' },
  { value: 'commerce.price', text: 'Price' },
  { value: 'commerce.productAdjective', text: 'Product Adjective' },
  { value: 'commerce.productMaterial', text: 'Product Material' },
  { value: 'commerce.product', text: 'Product' },
  { text: '-- COMPANY --', value: 'Company', disabled: true },
  { value: 'company.suffixes', text: 'Suffixes' },
  { value: 'company.companyName', text: 'Company Name' },
  { value: 'company.companySuffix', text: 'Company Suffix' },
  { value: 'company.catchPhrase', text: 'Catch Phrase' },
  { value: 'company.bs', text: 'bs' },
  { value: 'company.catchPhraseAdjective', text: 'Catch Phrase Adjective' },
  { value: 'company.catchPhraseDescriptor', text: 'Catch Phrase Descriptor' },
  { value: 'company.catchPhraseNoun', text: 'Catch Phrase Noun' },
  { value: 'company.bsAdjective', text: 'Bs Adjective' },
  { value: 'company.bsBuzz', text: 'Bs Buzz' },
  { value: 'company.bsNoun', text: 'Bs Noun' },
  { text: '-- DATABASE --', value: 'database', disabled: true },
  { value: 'database.column', text: 'Column' },
  { value: 'database.type', text: 'Type' },
  { value: 'database.collation', text: 'Collation' },
  { value: 'database.engine', text: 'Engine' },
  { value: 'DATE', text: 'Date' },
  { value: 'date.past', text: 'Past' },
  { value: 'date.future', text: 'Future' },
  { value: 'date.between', text: 'Between' },
  { value: 'date.recent', text: 'Recent' },
  { value: 'date.soon', text: 'Soon' },
  { value: 'date.month', text: 'Month' },
  { value: 'date.weekday', text: 'Weekday' },
  { text: '-- FINANCE --', value: 'Finance', disabled: true },
  { value: 'finance.account', text: 'Account' },
  { value: 'finance.accountName', text: 'Account Name' },
  { value: 'finance.mask', text: 'Mask' },
  { value: 'finance.amount', text: 'Amount' },
  { value: 'finance.transactionType', text: 'Transaction Type' },
  { value: 'finance.currencyCode', text: 'Currency Code' },
  { value: 'finance.currencyName', text: 'Currency Name' },
  { value: 'finance.currencySymbol', text: 'Currency Symbol' },
  { value: 'finance.bitcoinAddress', text: 'Bitcoin Address' },
  { value: 'finance.ethereumAddress', text: 'Ethereum Address' },
  { value: 'finance.iban', text: 'Iban' },
  { value: 'finance.bic', text: 'Bic' },
  { text: '-- HACKER --', value: 'hacker', disabled: true },
  { value: 'hacker.abbreviation', text: 'Abbreviation' },
  { value: 'hacker.adjective', text: 'Adjective' },
  { value: 'hacker.noun', text: 'Noun' },
  { value: 'hacker.verb', text: 'Verb' },
  { value: 'hacker.ingverb', text: 'Ingverb' },
  { value: 'hacker.phrase', text: 'Phrase' },
  { value: 'hacker.randomize', text: 'Randomize' },
  { value: 'hacker.slugify', text: 'Slugify' },
  { value: 'hacker.shuffle', text: 'Shuffle' },
  { value: 'hacker.mustache', text: 'Mustache' },
  { value: 'hacker.userCard', text: 'UserCard' },

  { text: '-- IMAGE --', value: 'Image', disabled: true },
  { value: 'image.image', text: 'Image' },
  { value: 'image.avatar', text: 'Avatar' },
  { value: 'image.imageUrl', text: 'Image Url' },
  { value: 'image.abstract', text: 'Abstract' },
  { value: 'image.animals', text: 'Animals' },
  { value: 'image.business', text: 'Business' },
  { value: 'image.cats', text: 'Cats' },
  { value: 'image.city', text: 'City' },
  { value: 'image.food', text: 'Food' },
  { value: 'image.nightlife', text: 'Nightlife' },
  { value: 'image.fashion', text: 'Fashion' },
  { value: 'image.people', text: 'People' },
  { value: 'image.nature', text: 'Nature' },
  { value: 'image.sports', text: 'Sports' },
  { value: 'image.technics', text: 'Technics' },
  { value: 'image.transport', text: 'Transport' },
  { value: 'image.dataUri', text: 'Data Uri' },

  { text: '-- INTERNET --', value: 'Internet', disabled: true },
  { value: 'internet.avatar', text: 'Avatar' },
  { value: 'internet.email', text: 'Email' },
  { value: 'internet.exampleEmail', text: 'Example Email' },
  { value: 'internet.userName', text: 'User Name' },
  { value: 'internet.protocol', text: 'Protocol' },
  { value: 'internet.url', text: 'Url' },
  { value: 'internet.domainName', text: 'Domain Name' },
  { value: 'internet.domainSuffix', text: 'Domain Suffix' },
  { value: 'internet.domainWord', text: 'Domain Word' },
  { value: 'internet.ip', text: 'Ip' },
  { value: 'internet.ipv6', text: 'Ipv6' },
  { value: 'internet.userAgent', text: 'User Agent' },
  { value: 'internet.color', text: 'Color' },
  { value: 'internet.mac', text: 'Mac' },
  { value: 'internet.password', text: 'Password' },

  { text: '-- LOREM --', value: 'lorem', disabled: true },
  { value: 'lorem.word', text: 'Word' },
  { value: 'lorem.words', text: 'Words' },
  { value: 'lorem.sentence', text: 'Sentence' },
  { value: 'lorem.slug', text: 'Slug' },
  { value: 'lorem.sentences', text: 'Sentences' },
  { value: 'lorem.paragraph', text: 'Paragraph' },
  { value: 'lorem.paragraphs', text: 'Paragraphs' },
  { value: 'lorem.text', text: 'Text' },
  { value: 'lorem.lines', text: 'Lines' },

  { text: '-- NAME --', value: 'Name', disabled: true },
  { value: 'name.firstName', text: 'First Name' },
  { value: 'name.lastName', text: 'Last Name' },
  { value: 'name.findName', text: 'Full Name' },
  { value: 'name.jobTitle', text: 'Job Title' },
  { value: 'name.prefix', text: 'Prefix' },
  { value: 'name.suffix', text: 'Suffix' },
  { value: 'name.title', text: 'Title' },
  { value: 'name.jobDescriptor', text: 'Job Descriptor' },
  { value: 'name.jobArea', text: 'Job Area' },
  { value: 'name.jobType', text: 'Job Type' },

  { text: '-- PHONE --', value: 'phone', disabled: true },
  { value: 'phone.phoneNumber', text: 'Phone Number' },
  { value: 'phone.phoneNumberFormat', text: 'Phone Number Format' },
  { value: 'phone.phoneFormats', text: 'Phone Formats' },

  { text: '-- RANDOM --', value: 'Random', disabled: true },
  { value: 'random.number', text: 'Number' },
  { value: 'random.float', text: 'Float' },
  { value: 'random.arrayElement', text: 'Array Element' },
  { value: 'random.objectElement', text: 'Object Element' },
  { value: 'random.uuid', text: 'Uuid' },
  { value: 'random.boolean', text: 'Boolean' },
  { value: 'random.word', text: 'Word' },
  { value: 'random.words', text: 'Words' },
  { value: 'random.image', text: 'Image' },
  { value: 'random.locale', text: 'Locale' },
  { value: 'random.alphaNumeric', text: 'Alpha Numeric' },
  { value: 'random.hexaDecimal', text: 'Hexa Decimal' },

  { text: '-- SYSTEM --', value: 'system', disabled: true },
  { value: 'system.fileName', text: 'File Name' },
  { value: 'system.commonFileName', text: 'Common File Name' },
  { value: 'system.mimeType', text: 'Mime Type' },
  { value: 'system.commonFileType', text: 'Common File Type' },
  { value: 'system.commonFileExt', text: 'Common File Extension' },
  { value: 'system.fileType', text: 'File Type' },
  { value: 'system.fileExt', text: 'File Ext' },
  { value: 'system.directoryPath', text: 'Directory Path' },
  { value: 'system.filePath', text: 'File Path' },
  { value: 'system.semver', text: 'Semver' }
];
